// Shared enums mirroring the Prisma schema enums.
// Keep in sync with apps/api/prisma/schema.prisma.

export enum AcquisitionType {
  PURCHASED = 'PURCHASED',
  DONATED_DEMO = 'DONATED_DEMO',
  DONATED_GIVEABLE = 'DONATED_GIVEABLE',
}

export enum OperationalStatus {
  AVAILABLE_FOR_LOAN = 'AVAILABLE_FOR_LOAN',
  RESERVED = 'RESERVED',
  ON_LOAN = 'ON_LOAN',
  ALLOCATED_OUT = 'ALLOCATED_OUT',
  AVAILABLE_FOR_DEMO = 'AVAILABLE_FOR_DEMO',
  ON_DEMO_VISIT = 'ON_DEMO_VISIT',
  DECOMMISSIONED = 'DECOMMISSIONED',
}

export enum Condition {
  GOOD = 'GOOD',
  FAIR = 'FAIR',
  POOR = 'POOR',
}

export enum DeviceCategory {
  DIGITAL_MAGNIFIER = 'DIGITAL_MAGNIFIER',
  CCTV_MAGNIFIER = 'CCTV_MAGNIFIER',
  TEXT_TO_SPEECH = 'TEXT_TO_SPEECH',
  SMARTPHONE = 'SMARTPHONE',
  TABLET = 'TABLET',
  MONITOR = 'MONITOR',
  OTHER = 'OTHER',
}

export enum Role {
  ADMIN = 'ADMIN',
  STAFF = 'STAFF',
}

export enum AuditEvent {
  ITEM_CREATED = 'ITEM_CREATED',
  ITEM_EDITED = 'ITEM_EDITED',
  ACQUISITION_RECLASSIFIED = 'ACQUISITION_RECLASSIFIED',
  RESERVED = 'RESERVED',
  RESERVATION_CANCELLED = 'RESERVATION_CANCELLED',
  LOAN_ISSUED = 'LOAN_ISSUED',
  LOAN_RETURNED = 'LOAN_RETURNED',
  LOAN_CONVERTED_TO_ALLOCATION = 'LOAN_CONVERTED_TO_ALLOCATION',
  ALLOCATED_DIRECTLY = 'ALLOCATED_DIRECTLY',
  DEMO_VISIT_STARTED = 'DEMO_VISIT_STARTED',
  DEMO_VISIT_RETURNED = 'DEMO_VISIT_RETURNED',
  DECOMMISSIONED = 'DECOMMISSIONED',
  ARCHIVED = 'ARCHIVED',
  ARCHIVE_RESTORED = 'ARCHIVE_RESTORED',
  SALE_FLAGGED = 'SALE_FLAGGED',
  SALE_FLAG_REMOVED = 'SALE_FLAG_REMOVED',
  USER_CREATED = 'USER_CREATED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
}

export enum NotificationType {
  LOAN_OVERDUE = 'LOAN_OVERDUE',
  RESERVATION_EXPIRED = 'RESERVATION_EXPIRED',
  DEMO_VISIT_OVERDUE = 'DEMO_VISIT_OVERDUE',
}

export enum ReservationCloseReason {
  CONVERTED_TO_LOAN = 'CONVERTED_TO_LOAN',
  CANCELLED = 'CANCELLED',
  DECOMMISSIONED = 'DECOMMISSIONED',
}

export enum LoanCloseReason {
  RETURNED = 'RETURNED',
  CONVERTED_TO_ALLOCATION = 'CONVERTED_TO_ALLOCATION',
  DECOMMISSIONED = 'DECOMMISSIONED',
}

export enum DemoVisitCloseReason {
  RETURNED = 'RETURNED',
  DECOMMISSIONED = 'DECOMMISSIONED',
}
